# Generated by Django 4.2.4 on 2023-08-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(default=None, max_length=128, primary_key=True, serialize=False)),
                ('credit', models.IntegerField(default=0)),
                ('totalLoan', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
