# Generated by Django 4.2.4 on 2023-08-24 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userService', '0001_initial'),
        ('treasuryService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowDate', models.DateTimeField(auto_now_add=True)),
                ('returnDate', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasuryService.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userService.profile')),
            ],
        ),
    ]
