# Generated by Django 4.2.4 on 2023-08-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasuryService', '0001_initial'),
        ('userService', '0001_initial'),
        ('loanService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='treasuryService.book'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='userService.profile'),
        ),
    ]
