# Generated by Django 4.2.4 on 2023-08-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanService', '0002_alter_loan_book_alter_loan_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='returnDate',
        ),
    ]
