# Generated by Django 4.2.4 on 2023-08-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('pageNumbers', models.SmallIntegerField(null=True)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
    ]
