# Generated by Django 4.2.4 on 2023-08-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('pagesNumber', models.SmallIntegerField(null=True)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
    ]
