# Generated by Django 4.2.4 on 2023-08-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasuryService', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pageNumbers',
            new_name='pagesNumber',
        ),
    ]
