# Generated by Django 4.2.4 on 2023-08-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasuryService', '0002_rename_pagenumbers_book_pagesnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
